name: CI

on:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 2
    strategy:
      fail-fast: false
      matrix:
        include:
        - java: 8
          os: macos-latest
          arch: arm64
          runner: macos-latest
          distribution: zulu
          expander_leg: macos-latest-8-arm64
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
    - name: Set up JDK
      uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 #v6.0.1
      with:
        java-version: ${{ matrix.java }}
        distribution: ${{ matrix.distribution || 'temurin' }}
    - name: Build
      run: ./mvnw --no-transfer-progress -B clean verify -Pfull,all --file 
        pom.xml
    name: build [${{ matrix.expander_leg }}]
